# -*- coding: utf-8 -*-
"""factorial_main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ToXEI3iKRjGcbN4IFRWYLpvqc6QxE7oH
"""

import time
import numpy as np
from factorial_operation import factorial_python, factorial_numpy, factorial_cython

# Input value for factorial calculation
n = 15

# Calculate factorial using Python implementation
start_time = time.time()
result_python = factorial_python(n)
end_time = time.time()
time_python = end_time - start_time
print(f"Factorial using Python: {result_python}, Time taken: {time_python} seconds")

# Calculate factorial using NumPy implementation
start_time = time.time()
result_numpy = factorial_numpy(n)
end_time = time.time()
time_numpy = end_time - start_time
print(f"Factorial using NumPy: {result_numpy}, Time taken: {time_numpy} seconds")

# Calculate factorial using Cython implementation
start_time = time.time()
result_cython = factorial_cython(n)
end_time = time.time()
time_cython = end_time - start_time
print(f"Factorial using Cython: {result_cython}, Time taken: {time_cython} seconds")