# -*- coding: utf-8 -*-
"""factorial_operation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tr7s65i04ZJG-RwWqjNCZwecbC__I4zF
"""

import numpy as np

def factorial_python(n):       # Calculate factorial using Python implementation

    if n == 0:
        return 1
    else:
        return n * factorial_python(n-1)

def factorial_numpy(n):         # Calculate factorial using NumPy implementation


    return np.prod(np.arange(1, n+1))

def factorial_cython(n):   #Calculate factorial using Cython implementation.
  from factorial_cython import factorial_cython_impl
  return factorial_cython_impl(n)